/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface NavItem {
  icon: string;
  text: string;
}

const Navigation: React.FC = () => {
  const navItems: NavItem[] = [
    {
      icon: "/images/Accommodation.svg",
      text: "Accommodation",
    },
    {
      icon: "/images/Flights.svg",
      text: "Flights",
    },
    {
      icon: "/images/car-rentals.svg",
      text: "Car Rentals",
    },
    {
      icon: "/images/Sightseeing.svg",
      text: "Sightseeing",
    },
    {
      icon: "/images/Transportation.svg",
      text: "Transportation",
    },
  ];

  return (
    <nav className="flex flex-col justify-center text-lg text-white max-md:max-w-full">
      <div className="flex gap-5 justify-between self-end font-semibold">
        <img
          loading="lazy"
          src="/images/search-white.svg"
          className="shrink-0 w-6 aspect-square"
          alt=""
        />
        <img
          loading="lazy"
          src="/images/globe.svg"
          className="shrink-0 w-6 aspect-square"
          alt=""
        />
        <img
          loading="lazy"
          src="/images/questions.svg"
          className="shrink-0 w-6 aspect-square"
          alt=""
        />
        <img
          loading="lazy"
          src="/images/bell.svg"
          className="shrink-0 w-6 aspect-square"
          alt=""
        />
        <div className="flex gap-1">
          <img
            loading="lazy"
            src="/images/user.svg"
            className="shrink-0 w-6 aspect-square"
            alt=""
          />
          <div className="my-auto">Jane Doe</div>
        </div>
      </div>
      <div className="flex gap-5 justify-between mt-4 max-md:flex-wrap">
        {navItems.map((item, index) => (
          <div key={index} className="flex gap-1 whitespace-nowrap">
            <img
              loading="lazy"
              src={item.icon}
              className="shrink-0 w-6 aspect-square"
              alt=""
            />
            <div className="my-auto">{item.text}</div>
          </div>
        ))}
      </div>
    </nav>
  );
};

export default Navigation;
