/**
 * This code was generated by Builder.io.
 */
import React from "react";

const HotelImage: React.FC = () => {
  return (
    <aside className="flex flex-col ml-5 w-[23%] max-md:ml-0 max-md:w-full">
      <img
        loading="lazy"
        src="/images/sidebar.png"
        className="grow shrink-0 max-w-full aspect-[0.57] w-[259px] max-md:mt-10"
        alt="reviews"
      />
    </aside>
  );
};

export default HotelImage;
