/**
 * This code was generated by Builder.io.
 */
import { BookingDto } from "@/shared";
import React from "react";

type BookingConfirmationProps = {
  details: BookingDto;
  id: string;
};
const BookingConfirmation: React.FC<BookingConfirmationProps> = ({
  details,
  id,
}) => {
  return (
    <main className='max-w-[1240px] max-md:max-w-full mx-auto'>
      <div className='flex items-center justify-between p-4 border-b border-gray-200'>
        <div>
          <div className='flex items-center space-x-2'>
            <div className='flex items-center text-yellow-500'>
              {[...Array(5)].map((_, index) => (
                <svg
                  key={index}
                  xmlns='http://www.w3.org/2000/svg'
                  className='h-5 w-5'
                  fill='currentColor'
                  viewBox='0 0 24 24'
                >
                  <path d='M12 .587l3.668 7.568 8.332 1.151-6.064 5.981 1.421 8.304-7.357-3.872-7.357 3.872 1.421-8.304-6.064-5.981 8.332-1.151z' />
                </svg>
              ))}
            </div>
            <div className='bg-yellow-400 text-white text-sm font-bold px-1.5 py-0.5 rounded-full flex items-center'>
              <span>👍</span>
            </div>
          </div>
          <h1 className='text-2xl font-bold mt-2 text-black'>
            {details.hotel}
          </h1>
          <div className='flex items-center text-sky-600 mt-2'>
            <svg
              xmlns='http://www.w3.org/2000/svg'
              className='h-5 w-5 mr-1'
              fill='none'
              viewBox='0 0 24 24'
              stroke='currentColor'
            >
              <path
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth='2'
                d='M16.88 3.549a6.5 6.5 0 00-9.76 8.451L12 21l4.35-8.999A6.5 6.5 0 0016.88 3.55z'
              />
            </svg>
            <span>
              25 Boulevard du Souverain, Watermaal-Bosvoorde /
              Watermael-Boitsfort, 1170 Brussels, Belgium
            </span>
          </div>
          <a href='#' className='text-sky-600 underline mt-1 block'>
            Great location - show map
          </a>
        </div>
        <div className='flex items-center space-x-4'>
          <button className='flex items-center border border-sky-600 text-sky-600 px-4 py-2 rounded-lg'>
            <svg
              xmlns='http://www.w3.org/2000/svg'
              className='h-5 w-5 mr-2'
              fill='none'
              viewBox='0 0 24 24'
              stroke='currentColor'
            >
              <path
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth='2'
                d='M19 9l-7 7-7-7'
              />
            </svg>
            Check available dates
          </button>
          <div className='flex items-center text-sky-600'>
            <svg
              xmlns='http://www.w3.org/2000/svg'
              className='h-6 w-6 mr-2'
              fill='none'
              viewBox='0 0 24 24'
              stroke='currentColor'
            >
              <path
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth='2'
                d='M12 4.5v15m7-7.5H5'
              />
            </svg>
            <span>We Price Match</span>
          </div>
        </div>
      </div>
      {/* ----------------------- */}
      <div className='flex mx-auto bg-white rounded-xl overflow-hidden'>
        {/* Left Section: Reservation & Car Rental */}
        <div className='w-2/4 p-2'>
          {/* header */}
          <div className='p-2'>
            <h2 className='font-bold text-black text-xl'>
              🏨 Here is your reservation confirmation
            </h2>
          </div>
          {/* Hotel Details */}
          <div className='p-2'>
            <h2 className='text-green-600 text-xl font-bold'>
              {details.hotel}
            </h2>
            <div className='mt-2'>
              <div className='flex'>
                <div className='mr-20'>
                  <p className='font-bold text-black'>Check-in</p>
                  <p className='text-sky-600'>{details.checkIn}</p>
                </div>
                <div>
                  <p className='font-bold text-black'>Check-out</p>
                  <p className='text-sky-600'>{details.checkOut}</p>
                </div>
              </div>
              <p className='mt-4 font-bold text-black'>Rooms and guests</p>
              <p className='text-sky-600'>{`${details.numberOfRooms} Room, ${details.numberOfGuests} Guests`}</p>
            </div>

            {/* Reservation ID */}
            <div className='mt-6'>
              <p className='font-bold text-black'>
                YOUR RESERVATION ID:
                <span className='text-black'> {id}</span>
              </p>
              <div className='mt-3'>
                <p className='text-base text-black'>Reservation date</p>
                <p className='text-sky-600'>Mon 10 Jul</p>
              </div>
            </div>

            {/* EUDI Wallet Button */}
            <div className='bg-sky-600 text-white p-4 text-center mt-4'>
              <button className='w-full p-2 font-bold'>
                Issue your reservation confirmation to EUDI Wallet
              </button>
            </div>
          </div>
        </div>

        <div className='w-1/4 p-2'>
          {/* Car Rental Section */}
          <div className=''>
            {/* header */}
            <div className='p-2'>
              <h2 className='font-bold text-black text-xl'>
                🚗 Car rental information
              </h2>
            </div>
            <div className=''>
              <img
                src='https://via.placeholder.com/150'
                alt='Car Image'
                className='w-32 h-24 object-cover rounded-md'
              />
              <span className='text-black font-bold text-sm'>
                To continue booking your car rental, you must{" "}
                <a href='#' className='text-sky-600 underline'>
                  sign your contract
                </a>{" "}
                with the rental service electronically.
              </span>
            </div>

            {/* Car Rental Button */}
            <div className='bg-sky-600 text-white p-4 text-center mt-4'>
              <button className='w-full p-2 font-bold'>
                Sign your car rental contract
              </button>
            </div>
          </div>
        </div>
        {/* Right Section: Reviews & Map */}
        <div className='w-1/4 p-4'>
          {/* Review Box */}
          <div className='bg-white shadow p-4 rounded-md'>
            <div className='flex items-center'>
              <div className='text-sky-600 text-3xl font-bold'>8.5</div>
              <div className='ml-2'>
                <p className='font-bold'>Very good</p>
                <p className='text-gray-500 text-sm'>2,477 reviews</p>
              </div>
            </div>
            <p className='text-sm mt-4 text-black'>
              Great that there is an option for early and late checkout as it
              allowed us to make the most of the weekend we were there for.
              Great hotel room...
            </p>
            <div className='mt-2 flex items-center'>
              <p className='text-sm text-gray-500'>Tazmein</p>
              <img
                src='https://via.placeholder.com/16'
                alt='Country Flag'
                className='ml-2 rounded-full'
              />
              <p className='text-sm text-gray-500 ml-1'>United Kingdom</p>
            </div>
            <p className='mt-4 text-gray-500 text-sm'>
              Free WiFi <span className='text-sky-600 font-bold ml-2'>8.6</span>
            </p>
          </div>

          {/* Map Button */}
          <div className='mt-4 bg-white p-4 shadow rounded-md text-center'>
            <button className='bg-sky-600 text-white p-2 w-full font-bold'>
              Show on map
            </button>
            <img
              src='https://via.placeholder.com/200'
              alt='Map Preview'
              className='w-full mt-4 rounded-md'
            />
          </div>
        </div>
      </div>
      {/* ----------------------- */}
    </main>
  );
};

export default BookingConfirmation;
