/**
 * This code was generated by Builder.io.
 */
import { BookingDto } from "@/shared";
import React from "react";
import HotelLocation from "../HotelLocation";

type BookingConfirmationProps = {
  details: BookingDto;
  id: string;
  deviceType: string;
};
const BookingConfirmation: React.FC<BookingConfirmationProps> = ({
  details,
  id,
  deviceType,
}) => {
  console.log(deviceType);
  return (
    <main className='max-w-[1240px] max-md:max-w-full mx-auto'>
      <HotelLocation />
      {/* ----------------------- */}
      <div className='flex mx-auto bg-white rounded-xl overflow-hidden'>
        {/* Left Section: Reservation & Car Rental */}
        <div className='w-2/4 p-2'>
          {/* header */}
          <div className='p-2'>
            <h2 className='font-bold text-black text-xl'>
              🏨 Here is your reservation confirmation
            </h2>
          </div>
          {/* Hotel Details */}
          <div className='p-2'>
            <h2 className='text-green-600 text-xl font-bold'>
              {details.hotel}
            </h2>
            <div className='mt-2'>
              <div className='flex'>
                <div className='mr-20'>
                  <p className='font-bold text-black'>Check-in</p>
                  <p className='text-sky-600'>{details.checkIn}</p>
                </div>
                <div>
                  <p className='font-bold text-black'>Check-out</p>
                  <p className='text-sky-600'>{details.checkOut}</p>
                </div>
              </div>
              <p className='mt-4 font-bold text-black'>Rooms and guests</p>
              <p className='text-sky-600'>{`${details.numberOfRooms} Room, ${details.numberOfGuests} Guests`}</p>
            </div>

            {/* Reservation ID */}
            <div className='mt-6'>
              <p className='font-bold text-black'>
                YOUR RESERVATION ID:
                <span className='text-black'> {id}</span>
              </p>
              <div className='mt-3'>
                <p className='text-base text-black'>Reservation date</p>
                <p className='text-sky-600'>Mon 10 Jul</p>
              </div>
            </div>

            {/* EUDI Wallet Button */}

            <div className='flex gap-2 justify-center py-2 pr-20 mt-3 text-sm text-center text-white bg-white max-md:flex-wrap max-md:pr-5'>
              {deviceType === "mobile" ? (
                <button className='flex justify-betweem px-2 py-4 bg-sky-600 rounded-sm'>
                  <img
                    loading='lazy'
                    src='/images/eudiwallet.svg'
                    className='mt-2 w-12 aspect-[1.41] ml-4'
                    alt='EUDI Wallet'
                  />
                  <div>Issue your reservation confirmation to EUDI Wallet</div>
                </button>
              ) : (
                <button
                  onClick={() => console.log("acan qr code")}
                  className='flex flex-col justify-center px-2 py-4 bg-sky-600 rounded-sm max-md:px-5'
                >
                  <div className='flex items-center'>
                    {/* //TODO change hardcoded value */}
                    {false && (
                      <svg
                        className='animate-spin h-5 w-5 text-white mr-2'
                        xmlns='http://www.w3.org/2000/svg'
                        fill='none'
                        viewBox='0 0 24 24'
                      >
                        <circle
                          className='opacity-25'
                          cx='12'
                          cy='12'
                          r='10'
                          stroke='currentColor'
                          strokeWidth='4'
                        ></circle>
                        <path
                          className='opacity-75'
                          fill='currentColor'
                          d='M4 12a8 8 0 018-8v8h8a8 8 0 01-8 8v-8H4z'
                        ></path>
                      </svg>
                    )}
                    <div>
                      Issue your reservation confirmation to EUDI Wallet
                    </div>
                  </div>
                  <img
                    loading='lazy'
                    src='/images/qrcode.svg'
                    className='self-center mt-2 aspect-square w-[41px]'
                    alt='QR Code'
                  />
                </button>
              )}
            </div>
          </div>
        </div>

        <div className='w-1/4 p-2'>
          {/* Car Rental Section */}
          <div className=''>
            {/* header */}
            <div className='p-2'>
              <h2 className='font-bold text-black text-xl'>
                🚗 Car rental information
              </h2>
            </div>
            <div className=''>
              <img
                src='https://via.placeholder.com/150'
                alt='Car Image'
                className='w-32 h-24 object-cover rounded-md'
              />
              <span className='text-black font-bold text-sm'>
                To continue booking your car rental, you must{" "}
                <a href='#' className='text-sky-600 underline'>
                  sign your contract
                </a>{" "}
                with the rental service electronically.
              </span>
            </div>

            {/* Car Rental Button */}
            <div className='bg-sky-600 text-white p-4 text-center mt-4'>
              <button className='w-full p-2 font-bold'>
                Sign your car rental contract
              </button>
            </div>
          </div>
        </div>
        {/* Right Section: Reviews & Map */}
        <div className='w-1/4 p-4'>
          {/* Review Box */}
          <div className='bg-white shadow p-4 rounded-md'>
            <div className='flex items-center'>
              <div className='text-sky-600 text-3xl font-bold'>8.5</div>
              <div className='ml-2'>
                <p className='font-bold'>Very good</p>
                <p className='text-gray-500 text-sm'>2,477 reviews</p>
              </div>
            </div>
            <p className='text-sm mt-4 text-black'>
              Great that there is an option for early and late checkout as it
              allowed us to make the most of the weekend we were there for.
              Great hotel room...
            </p>
            <div className='mt-2 flex items-center'>
              <p className='text-sm text-gray-500'>Tazmein</p>
              <img
                src='https://via.placeholder.com/16'
                alt='Country Flag'
                className='ml-2 rounded-full'
              />
              <p className='text-sm text-gray-500 ml-1'>United Kingdom</p>
            </div>
            <p className='mt-4 text-gray-500 text-sm'>
              Free WiFi <span className='text-sky-600 font-bold ml-2'>8.6</span>
            </p>
          </div>

          {/* Map Button */}
          <div className='mt-4 bg-white p-4 shadow rounded-md text-center'>
            <button className='bg-sky-600 text-white p-2 w-full font-bold'>
              Show on map
            </button>
            <img
              src='https://via.placeholder.com/200'
              alt='Map Preview'
              className='w-full mt-4 rounded-md'
            />
          </div>
        </div>
      </div>
      {/* ----------------------- */}
    </main>
  );
};

export default BookingConfirmation;
