/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface FormFieldProps {
  label: string;
  icon: string;
}

const FormField: React.FC<FormFieldProps> = ({ label, icon }) => (
  <div className="flex flex-col justify-center px-2 py-1.5 w-full bg-white rounded-sm border border-solid border-black border-opacity-10">
    <div className="flex gap-2 justify-between p-2">
      <label className="my-auto">
        {label} <span className="text-red-600">*</span>
      </label>
      <img
        loading="lazy"
        src={icon}
        className="shrink-0 w-6 aspect-square"
        alt=""
      />
    </div>
  </div>
);

const BookingForm: React.FC = () => {
  return (
    <form className="flex flex-col w-[28%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col text-base text-red-600 text-opacity-70 max-md:mt-10">
        <FormField
          label="Hotel"
          icon="images/search.svg"
        />
        <FormField
          label="Location"
          icon="images/search.svg"
        />
        <FormField
          label="Number of guests"
          icon="images/arrow-down.svg"
        />
        <FormField
          label="Number of rooms"
          icon="images/arrow-down.svg"
        />
        <div className="flex gap-2.5 mt-6">
          <div className="flex flex-col justify-center items-start px-4 py-3.5 bg-white rounded-sm border border-solid border-black border-opacity-10 max-md:pr-5">
            <div className="flex gap-2">
              <label htmlFor="checkIn" className="my-auto">
                Check-in <span className="text-red-600">*</span>
              </label>
              <img
                loading="lazy"
                src="images/datepicker.svg"
                className="shrink-0 w-6 aspect-square"
                alt=""
              />
            </div>
          </div>
          <div className="flex flex-col justify-center px-4 py-3.5 bg-white rounded-sm border border-solid border-black border-opacity-10">
            <div className="flex gap-2">
              <label htmlFor="checkOut" className="my-auto">
                Check-out <span className="text-red-600">*</span>
              </label>
              <img
                loading="lazy"
                src="images/datepicker.svg"
                className="shrink-0 w-6 aspect-square"
                alt=""
              />
            </div>
          </div>
        </div>
      </div>
    </form>
  );
};

export default BookingForm;
