/**
 * This code was generated by Builder.io.
 */
import useAppStore from "@/store/appStore";
import { useBookingStore } from "@/store/bookingStore";
import React from "react";

const HotelDescription: React.FC = () => {
  const deviceType = useAppStore((state) => state.deviceType);
  const { changeModalStatus } = useAppStore();
  const { createBooking } = useBookingStore();
  const handleBooking = async () => {
    await createBooking({
      hotel: "ABC hotel",
      location: "Patrara",
      numberOfGuests: 5,
      numberOfRooms: 2,
      checkIn: "2024-08-26T14:30:00.123Z",
      checkOut: "2024-08-27T14:30:00.123Z",
    });

    changeModalStatus();
  };
  return (
    <section className="flex flex-col ml-5 w-[49%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col text-xs max-md:mt-10 max-md:max-w-full">
        <p className="text-black max-md:max-w-full">
          Oasis Hotel has a garden, terrace, a restaurant and bar in Brussels.
          With free WiFi, this 4-star hotel offers room service and a 24-hour
          front desk. There is a spa and wellness centre with an outdoor
          swimming pool, indoor pool and fitness centre, as well as a sauna.
          <br />
          <br />
          The hotel will provide guests with air-conditioned rooms offering a
          desk, a kettle, a fridge, a safety deposit box, a flat-screen TV and a
          private bathroom with a shower. Some rooms include a kitchenette with
          a dishwasher, an oven and a microwave. At Oasis Hotel rooms come with
          bed linen and towels.
          <br />
          <br />
          The accommodation offers a buffet or continental breakfast. The
          wellness area at Oasis Hotel is comprised of a hot tub and a hammam.
          <br />
          <br />
        </p>
        <div className="justify-center p-2 mt-9 max-w-full font-bold rounded bg-neutral-50 text-black text-opacity-90 w-[312px]">
          To continue booking your travel plan, issue the requested credentials
          using EUDI Wallet:
        </div>
        <div className="flex gap-2 justify-center py-2 pr-20 mt-3 text-sm text-center text-white bg-white max-md:flex-wrap max-md:pr-5">
          {deviceType === "mobile" ? (
            <button className="flex flex-col justify-center px-2 py-4 bg-sky-600 rounded-sm">
              <div>Book using EUDI Wallet</div>
              <img
                loading="lazy"
                src="images/eudiwallet.svg"
                className="self-center mt-2 w-12 aspect-[1.41]"
                alt="EUDI Wallet"
              />
            </button>
          ) : (
            <button
              onClick={handleBooking}
              className="flex flex-col justify-center px-2 py-4 bg-sky-600 rounded-sm max-md:px-5"
            >
              <div>Scan QR code</div>
              <img
                loading="lazy"
                src="images/qrcode.svg"
                className="self-center mt-2 aspect-square w-[41px]"
                alt="QR Code"
              />
            </button>
          )}
        </div>
      </div>
    </section>
  );
};

export default HotelDescription;
