/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import MainContent from "./MainContent";
import Footer from "./Footer";

const TravelBook: React.FC = () => {
  return (
    <div className="flex flex-col pb-10 bg-white">
      <Header />
      <MainContent />
      <Footer />
    </div>
  );
};

export default TravelBook;
